# Generated by Django 4.1.1 on 2022-10-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_artist_id_alter_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(related_name='song', to='App.artist'),
        ),
    ]
